package telas;

import ferramentas.Arquivo;
import ferramentas.Globais;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import modelo.Personagem;

/**
 *
 * @author luisk
 */
public class TelaInicial extends javax.swing.JFrame {

    Arquivo objArquivo;
    Personagem objPersonagem;
 

    public TelaInicial() {
        initComponents();
        ajustarImagem("/imagens/vila.jpg", lblVila);
        Globais.tocarSom("/src/song/instrumental.wav");
    }

    private void ajustarImagem(String caminho, JLabel label) {
        try {

            ImageIcon imageIcon = new ImageIcon(getClass().getResource(caminho));
            Image img = imageIcon.getImage();
            Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledimageIcon = new ImageIcon(imgScale);
            label.setIcon(scaledimageIcon);

        } catch (Exception ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtSeumadruga = new javax.swing.JRadioButton();
        rbtChiquinha = new javax.swing.JRadioButton();
        rbtChaves = new javax.swing.JRadioButton();
        rbtKiko = new javax.swing.JRadioButton();
        rbtDonaflorinda = new javax.swing.JRadioButton();
        rbtBruxa = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnAvancar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblVila = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        buttonGroup1.add(rbtSeumadruga);
        rbtSeumadruga.setText("Seu Madruga");
        rbtSeumadruga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSeumadrugaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtChiquinha);
        rbtChiquinha.setText("Chiquinha");
        rbtChiquinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtChiquinhaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtChaves);
        rbtChaves.setText("Chaves");
        rbtChaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtChavesActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtKiko);
        rbtKiko.setText("Kiko");
        rbtKiko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtKikoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtDonaflorinda);
        rbtDonaflorinda.setText("Dona Florinda");
        rbtDonaflorinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDonaflorindaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtBruxa);
        rbtBruxa.setText("Bruxa do 71");
        rbtBruxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBruxaActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Escolha um personagem");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));

        btnAvancar.setText("Iniciar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtChaves)
                    .addComponent(rbtKiko))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtSeumadruga)
                            .addComponent(rbtChiquinha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtBruxa)
                                .addGap(64, 64, 64)
                                .addComponent(btnAvancar))
                            .addComponent(rbtDonaflorinda)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtChiquinha)
                    .addComponent(rbtChaves)
                    .addComponent(rbtDonaflorinda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtSeumadruga)
                    .addComponent(rbtKiko)
                    .addComponent(rbtBruxa)
                    .addComponent(btnAvancar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 580, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AS PESSOAS BOAS DEVEM AMAR SEU INIMIGOS!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 580, -1));

        lblVila.setText("vila");
        getContentPane().add(lblVila, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 36, 580, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtDonaflorindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDonaflorindaActionPerformed
        objPersonagem = new Personagem();
        objPersonagem.setCasa("14");
        objPersonagem.setNome("Dona Florinda");
        objPersonagem.setVida(95);
        objPersonagem.setAtaque(35);
    }//GEN-LAST:event_rbtDonaflorindaActionPerformed

    private void rbtBruxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtBruxaActionPerformed
        objPersonagem = new Personagem();
        objPersonagem.setCasa("71");
        objPersonagem.setNome("Bruxa do 71");
        objPersonagem.setVida(70);
        objPersonagem.setAtaque(22);
    }//GEN-LAST:event_rbtBruxaActionPerformed

    private void rbtKikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtKikoActionPerformed
        objPersonagem = new Personagem();
        objPersonagem.setCasa("14");
        objPersonagem.setNome("Kiko");
        objPersonagem.setVida(95);
        objPersonagem.setAtaque(20);
    }//GEN-LAST:event_rbtKikoActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        avancar();
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void rbtChavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtChavesActionPerformed

        objPersonagem = new Personagem();
        objPersonagem.setCasa("8");
        objPersonagem.setNome("Chaves");
        objPersonagem.setVida(70);
        objPersonagem.setAtaque(30);

    }//GEN-LAST:event_rbtChavesActionPerformed

    private void rbtChiquinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtChiquinhaActionPerformed
        objPersonagem = new Personagem();
        objPersonagem.setCasa("72");
        objPersonagem.setNome("Chiquinha");
        objPersonagem.setVida(90);
        objPersonagem.setAtaque(25);
    }//GEN-LAST:event_rbtChiquinhaActionPerformed

    private void rbtSeumadrugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSeumadrugaActionPerformed
        objPersonagem = new Personagem();
        objPersonagem.setCasa("72");
        objPersonagem.setNome("Seu Madruga");
        objPersonagem.setVida(80);
        objPersonagem.setAtaque(15);
    }//GEN-LAST:event_rbtSeumadrugaActionPerformed
   
    private void avancar() {
        try {
            //Enviar os dados da Classe escolhida para a tela Confronto
            //   definirOponente();
            TelaJogo tela = new TelaJogo(this.objPersonagem);

            tela.setVisible(true); //Mostra a tela de confronto
            //Colocar a tela atual não visivel
            this.setVisible(false);

        } catch (Exception ex) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblVila;
    private javax.swing.JRadioButton rbtBruxa;
    private javax.swing.JRadioButton rbtChaves;
    private javax.swing.JRadioButton rbtChiquinha;
    private javax.swing.JRadioButton rbtDonaflorinda;
    private javax.swing.JRadioButton rbtKiko;
    private javax.swing.JRadioButton rbtSeumadruga;
    // End of variables declaration//GEN-END:variables
}
